# Generated by Django 3.1.7 on 2021-03-09 22:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('[a-zA-Z]{4,15}', 'Invalid brand name use only letters, min length: 4 max length: 15')])),
                ('model', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('[a-zA-Z]{2,15}', 'Invalid brand name use only letters, min length: 2 max length: 15')])),
                ('produced_date', models.DateField()),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(5000), django.core.validators.MaxValueValidator(1000000)])),
                ('vin_code', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator('')])),
                ('license_plate', models.CharField(max_length=8, unique=True, validators=[django.core.validators.RegexValidator('[A-Z]{2}[0-9]{4}[A-Z]{2}', 'Invalid license plate. Example: AA2222AA')])),
                ('description', models.TextField(blank=True, default='New car', max_length=255)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'car',
                'db_table': 'cars',
            },
        ),
    ]
