# Generated by Django 3.1.7 on 2021-03-09 23:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='model',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('[a-zA-Z]{2,15}', 'Invalid model name use only letters, min length: 2 max length: 15')]),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='vin_code',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator('VIN[0-9]{5}', 'Invalid VIN code. Example: ')]),
        ),
    ]
